{{- $appPort := .Values.app.port -}}
{{- $nginxPort := .Values.nginx.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: app
          image: {{ .Values.registry }}/edo-api:{{ .Release.Namespace }}-{{ .Chart.Version }}
          ports:
            - containerPort: {{ $appPort }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: {{ $appPort }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: {{ $appPort }}
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-env
        - name: edo-nginx
          image: nginx:1.16.0-alpine
          ports:
            - containerPort: {{ $nginxPort }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: {{ $nginxPort }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: {{ $nginxPort }}
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-nginx

          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: edo-nginx-config
            subPath: nginx.conf
            readOnly: true
      volumes:
      - configMap:
          name: {{ .Chart.Name }}-nginx
        name: edo-nginx-config

      imagePullSecrets:
      - name: travel-key-registry