env:
  ASPNETCORE_ENVIRONMENT: "Production"
  HTDC_VAULT_ENDPOINT: "https://vault.dev.happytravel.com/v1/"
  HTDC_EDO_SENTRY_ENDPOINT: "https://db23cc3a191649f39a8d9087ded431f6@sentry.dev.happytravel.com/2"
ingress:
  enabled: true
  annotations:
    projectcontour.io/ingress.class: "contour"
    projectcontour.io/retry-on: "5xx"
    projectcontour.io/num-retries: "3"
    projectcontour.io/per-try-timeout: "120s"
    projectcontour.io/response-timeout: "120s"

  hosts:
    - host: edo-api.dev.happytravel.com
      paths: [/]

  tls: 
    - hosts:
        - edo-api.dev.happytravel.com